### ISSUE TITLE
Field Blocks - or contexts

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#13]
Will we be able to use field blocks or other contextual blocks in mini-layouts. If not, is that possible?

**Comment by docwilmot** [comment]
I was adding context last week, its a bit complex. Got distracted. Will push what I've got so far soon for testing.

**Comment by philsward** [comment]
@docwilmot looking for this too. Did you get around to getting this pushed?

**Comment by docwilmot** [comment]
Check out the new branch "contexts", will need some work.

**Comment by philsward** [comment]
Thanks @docwilmot 

You're right in saying it needs work. I'm having a hard time testing it in its current state and won't be able to provide much feedback on it as a result.

Curious what your thoughts are on "relationships"? That's what they are called on Drupal. Looking at what I have available with contexts, maybe it will work but it wasn't what I was expecting from the workflow.

As an example, I was hoping to choose a relationship to a content type -> product and have all of the fields that are available to the product content type available in the mini-panel.

**Comment by philsward** [comment]
Image fields don't seem to pull in through a "node" context. Everything else I've thrown at it (which isn't much) pulls in OK. I'm not sure if it's my setup or if image fields really are a problem.

**Comment by docwilmot** [comment]
> Image fields don't seem to pull in through a "node" context. 

Can youdescribe your steps please? Seems to work for me.

**Comment by philsward** [comment]
@docwilmot curious... I've always had problems wrapping my head around contexts... In this situation, if I use a context for a specific node ID, does it only pull the info from that node or all nodes that are of the same type? This might be my issue where I'm pointing to a node that doesn't have an image, but looking at a node that does but wasn't added as a context...

If this is how contexts work, I need to get a new issue going for relationships?

**Comment by philsward** [comment]
@docwilmot I got around to testing and yes, a context only pulls information from the node provided in the context.

Either relationships need to be added or maybe it could be accomplished with visibility conditions which kinda seem to act like the relationships in D7?

**Comment by philsward** [comment]
Back to topic, Context from path does not save for me, regardless of what I enter for the path.

**Comment by docwilmot** [comment]
OK, hell of a task, but I think I've coaxed Layout to allow contexts and relationships on mini layouts. Test away please.

**Comment by philsward** [comment]
You're a rockstar 😉

I'll give it a go, hopefully in the next few days.

**Comment by philsward** [comment]
I'm not having much luck getting the pop-up dialog when clicking on + Add context. The ajax spinner pops up with Please wait and that's all I get. Nothing shows up in console or watchdog.

**Comment by docwilmot** [comment]
Note your old mini layouts need to be deleted and cache cleared. I changed some stuff to do with titles.

**Comment by philsward** [comment]
@docwilmot I created a new layout when testing and still got the same errors. The old layouts had not been deleted at the time though.

**Comment by stpaultim** [comment]
This seems to be working in the current dev version. Closing this issue.
