### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#14]
How close do we think this is to release? 

I see that most of the reported bugs have been squashed. I just did some light experimenting and it seems to work as advertised. 

I have a feeling that this would get quite a bit of use quite quickly and hopefully additional feedback, once it is released.

**Comment by philsward** [comment]
I think #13 needs some attention before an official release but once that is hammered out I would say it's really close from the testing I've done.

**Comment by docwilmot** [comment]
AFAICT all issues have been addressed, so if we could get a round of testing, will launch this.

**Comment by stpaultim** [comment]
I've given it a pretty rigorous testing and it's quite good. But, I think I found at least one serious bug.

**Comment by stpaultim** [comment]
I did another round of testing and can't find any bugs.

**Comment by docwilmot** [comment]
Released!
