### ISSUE TITLE
Error on Save

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#16]
@docwilmot - sorry to report that i'm testing the latest version of the module and getting an error "Call to undefined function mini_layouts_block_layout_save()"

1. I have a fresh local site
2. Install and enable the latest version (branch = main)
3. Create a new mini-layout and get the error message on save.

**Comment by stpaultim** [comment]
Additional information from Watchdog:

Notice: Undefined index: path in MiniLayout->__construct() (line 56 of /app/modules/mini_layouts/layout.mini_layouts.class.inc).

Error: Call to undefined function mini_layouts_block_layout_save() in mini_layouts_add_block_form_submit() (line 532 of /app/modules/mini_layouts/mini_layouts.admin.inc).

**Comment by docwilmot** [comment]
Thats what happens if you make major changes and dont test them. Should still produce errors here and there, but should be able to create blocks now.

**Comment by docwilmot** [comment]
Fixed
