### ISSUE TITLE
Mini-layout Title is required

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#20]
The form to create a mini-layout does not require a title. However, without a title a mini-layout can't be used. 

![image](https://user-images.githubusercontent.com/3144571/143724700-92aa9adb-23f6-45f1-82da-dccbe3fc1faf.png)

But, when I go to add the mini-layout block, it is visible but not usable. 

![image](https://user-images.githubusercontent.com/3144571/143724721-a2f1dbc0-4fd2-4723-9d8a-c809d6f718ba.png)

**Comment by docwilmot** [comment]
I should mention that I changed some stuff and you'll need to delete your old minis and flush caches.

**Comment by docwilmot** [comment]
Ah I was wrong, just got home, and yes something is amiss.

**Comment by docwilmot** [comment]
Should be good

**Comment by philsward** [comment]
Tested. Working for me to have a mini-layout with only the Admin Label.
