### ISSUE TITLE
Blank Context Modal Before First Save With Errors That Follow Save

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/mini_layouts#21]
When creating a new mini-layout from scratch and clicking the +Add context link, a blank modal form is presented.

![image](https://user-images.githubusercontent.com/3436110/144318046-582dac9c-053d-49c7-bfbd-4a13d2eada4c.png)

Closing the modal box and saving the form results in the errors:

```
Notice: Trying to access array offset on value of type bool in layout_ajax_form_open_dialog() (line 2728 of ./core/modules/layout/layout.admin.inc).
Notice: Undefined index: title in mini_layouts_admin_configure_validate() (line 432 of ./modules/dev/mini_layouts/mini_layouts.admin.inc).
```

![image](https://user-images.githubusercontent.com/3436110/144318312-5767c9c8-b8c7-43e8-ad97-829472a1fe4b.png)

After that first save, the context form works properly as expected.

**Comment by docwilmot** [comment]
I've had to make context unavailable until the mini layout is first saved. To fix this otherwise would really complicate things.

**Comment by philsward** [comment]
Sounds good.

I haven't tested it yet, so tongue in cheek.

Is it worth having a placeholder for the context with some text saying "Save the mini-layout first to add contexts."?

**Comment by docwilmot** [comment]
> Is it worth having a placeholder for the context with some text saying "Save the mini-layout first to add contexts."?

That was part of the fix, yes.
