### ISSUE TITLE
Saving Mini-Layout Configuration Results In Undefined Index: Title Error

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/mini_layouts#22]
It took me a min to figure out how to reproduce, but finally nailed it.

Create more than 1 mini-layout and when saving the configuration (./configure) of any mini-layout, the error will show up on save.

`Notice: Undefined index: title in mini_layouts_admin_configure_validate() (line 432 of ./modules/dev/mini_layouts/mini_layouts.admin.inc).`

The very first mini-layout created and if there is only a single mini-layout in the system, will not result in the error.

Confirmed on two different environments, both had mini-layouts completely uninstalled and re-installed.

![image](https://user-images.githubusercontent.com/3436110/144320191-1fa87f96-305c-43db-9255-c0b61aebed5b.png)

**Comment by docwilmot** [comment]
Should be fixed
