### ISSUE TITLE
ERROR - Call to undefined function mini_layouts_admin_configure_validate()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#23]
@docwilmot - I just installed the current dev branch of Mini-Layouts into a fresh site and am getting this fatal error:

`Call to undefined function mini_layouts_admin_configure_validate()`

Steps to recreate:

1) Start with a fresh site and enabled Mini-Layouts (main branch)
2) Create a mini-layout with one of the new Mini Layout templates
2) Save mini-layout 

This triggers the above error. Here is a screenshot from immediately before error:

![Screenshot from 2021-12-14 20-38-19](https://user-images.githubusercontent.com/3144571/146112897-062af78c-cceb-4cc7-b66c-720ac4248102.png)

**Comment by docwilmot** [comment]
Forgot to delete that. Done.

**Comment by stpaultim** [comment]
My first test with a fresh install of the main branch triggered the same error. I'm starting over and trying again.

**Comment by stpaultim** [comment]
@docwilmot - hang on. This attempt went better. Sorry about false alarm. Still testing.

**Comment by stpaultim** [comment]
This is fixed. Thanks @docwilmot.
