### ISSUE TITLE
Every time you re-open a mini-layout, it says that it needs to be saved (even if you don't change it)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#24]
If you create and save a min-layout and then open it up again, it says `This form has unsaved changes. Click "Save layout" to make changes permanent or "Cancel" to discard changes.` even if you don't make any changes. 

I've seen similar problems with other forms in Backdrop, so this might not be a specific problem with mini-layouts.

**Comment by docwilmot** [comment]
I believe thats fixed now

**Comment by stpaultim** [comment]
Looks go to me.
