### ISSUE TITLE
Tweak user interface

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/mini_layouts#26]
Hi @docwilmot,

this module is a great enhancement for the core layout system. :+1:

I've noticed some room for improvement in the UI: the icons aren't very helpful:

![mini-layout-icons](https://user-images.githubusercontent.com/842066/147850821-583786bc-4166-4699-a42c-95c5b865885d.png)

These caused me some head-scratching - "heck, what will these look like?" :smirk:
Not sure, how much effort it would be to add custom icons, and if it's worth it.

Another thing I've noticed is that the layouts this module ships with use both classes, "container" and "container-fluid" - to my knowledge these classes are mutually exclusive (fixed width vs. flexible width). (Something that's also wrong in core templates, but that's another issue.)

![mini-layout-both-classes](https://user-images.githubusercontent.com/842066/147850918-34526d14-1999-4b9d-acd4-4f82eeae9c44.png)

In real life it's more likely that people construct their own (flexi) templates, anyway, so both findings aren't big problems.

**Comment by docwilmot** [comment]
Thanks @indigoxela we considered the OOTB layouts issue here: https://github.com/backdrop-contrib/mini_layouts/issues/12
I think this was the best compromise we could come up with. In short, flex layouts dont have icons, and regular layouts wont auto-install when this module is enabled.

**Comment by indigoxela** [comment]
> flex layouts dont have icons, and regular layouts wont auto-install...

So custom icons wouldn't be possible at all, is that correct?

How about the CSS classes (container + container-fluid instead of just one of them)? Would it be feasible to just add one of them? It's probably impossible to configure them via UI, I guess.

**Comment by docwilmot** [comment]
> So custom icons wouldn't be possible at all, is that correct?

Yes that was the conundrum here. 

The container issue is from core flexible templates, not this module, unfortunately. Here: https://github.com/backdrop/backdrop/blob/c7ebb0c40f59ca9fc0095d788483142efc7d9161/core/modules/layout/layout.theme.inc#L347

**Comment by indigoxela** [comment]
I see, so both, icons and css classes are out of scope of this module.
No problem, it's easy to delete the templates and build custom flexis, anyway.
