### ISSUE TITLE
There are multiple versions of module Block test in the installation.

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/mini_layouts#28]
The name of the Block test module file overlaps with a core test. This results in a warning message on the status page:

> There are multiple versions of module Block test in the installation.
> The competing module files are listed below. Only the first of the module versions in the list will be loaded.
> 
>  -   modules/mini_layouts/tests/mini_layouts_test/block_test.module
>  -   core/modules/block/tests/block_test/block_test.module

Proposed solution: rename the test-only module to something like `mini_layouts_block_test.module` to prevent that overlap.

https://github.com/backdrop-contrib/mini_layouts/tree/main/tests/mini_layouts_test

**Comment by docwilmot** [comment]
Tests are actually not configured in this module. That Block test was a copy paste from core Block when starting this module. Deleted it.
