### ISSUE TITLE
Improve display of block ID

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/mini_layouts#29]
I just opened up a mini-layout for the first time in a while and found the display of the block ids a bit jarring. 

![image](https://user-images.githubusercontent.com/3144571/170381868-6fbf01df-46a8-480c-b768-84f8bb2f2a85.png)

I don't have specific ideas yet for improvement, but will try to think of something constructive to suggest and/or to work on a PR sometime soon.

**Comment by stpaultim** [comment]
@docwilmot - Is this a bug? 

I've included Mini Layouts as a dependency for my "Welcome" module, because I wanted to place a footer blocks with columns into the default layouts that come with Backdrop CMS.

I'm doing this:
![image](https://user-images.githubusercontent.com/3144571/171554469-d2779806-147d-4aa8-a9f7-9114c6678697.png)

**Comment by stpaultim** [comment]
@docwilmot - Thanks. This looks much better. Same mini-layout as original post now looks like this:

![image](https://user-images.githubusercontent.com/3144571/171974674-ec749d91-b990-4aab-9330-fbaa03f8a053.png)

**Comment by stpaultim** [comment]
@docwilmot Has there been a regression. I'm testing module today and getting this when using one of the provided mini-layout templates for the first time. 

![image](https://github.com/backdrop-contrib/mini_layouts/assets/3144571/cb18d9e7-aa99-489b-a918-7ae947dff454)

* I spun up a demo Backdrop site on BackdropCMS.org
* I installed the latest dev branch of Mini-Layouts. 
* I created a mini-layout using the template "mini-1-2-3". 
* I clicked on Manage Blocks.

**Comment by docwilmot** [comment]
Cant reproduce this @stpaultim, it works fine for me, latest Backdrop dev, latest ML, PHP 8.1 and 8.2

**Comment by stpaultim** [comment]
I'll try again to reproduce.

**Comment by stpaultim** [comment]
@docwilmot I'm sorry, this was my fault. I thought I had tested with the dev branch, but in fact I think I was testing with the latest release.

I have confirmed that the latest release is still performing as described in this issue, but the dev branch has fixed this issue. 

Maybe we could issue a new release, since this is a pretty ugly bug that is part of the recommended release.

**Comment by stpaultim** [comment]
I am going to reopen this issue. Because, this is still what users are getting with the official release. It has been fixed in dev, but most users don't know that.

![image](https://github.com/backdrop-contrib/mini_layouts/assets/3144571/1a50aabf-16f8-47cb-a382-b2b0fa64ad22)

**Comment by stpaultim** [comment]
@docwilmot Thanks for the release. 

I think we can close this again.
