### ISSUE TITLE
Should it work out of the box or does it need extra styling?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/mini_layouts#33]
I wondered whether this module would solve a particular use case I have so decided to do a test.  The use case is to split the content in an existing layout between a sidebar (left) and main content block.  I wanted to use field blocks for some fields in the sidebar

1. I created a new site (1.22) in Lando and installed `devel` and `mini_layouts`
2. I used `devel` to create lots of nodes
3. I created a layout (regular) for posts using Boxton (no sidebars) called 'Articles' 
4. I created a flexible layout template for a single row with 2 columns (33%/67%)
5. I created a mini layout using the template, added the context of 'Get node ID from path' with `node/%`
6. I added main content to the 67% and the `field:field_block:node-field_image` to the sidebar
7. In the regular layout for articles I removed main content and added the mini layout block in its place.

This is what articles now look like:
![chrome_JAG074vcJA](https://user-images.githubusercontent.com/20357797/178933467-147e21ff-d269-4efd-a86a-b3c27ef69544.gif)

This is in Basis with no extra styling.

### layout.flexible.mini_content_sidebar.json
<details>

```json
{
    "_config_name": "layout.flexible.mini_content_sidebar",
    "name": "mini_content_sidebar",
    "title": "Mini Content Sidebar",
    "description": "Displays a sidebar next to the content in a mini layout",
    "rows": {
        "089793f2-3501-40ef-b800-d0d8a53c545b": {
            "contains": "region_4_8",
            "element": "div",
            "classes": "",
            "container": "container",
            "region_names": {
                "region_0": {
                    "label": "Sidebar",
                    "name": "mini-sidebar",
                    "region_class_enable": 0,
                    "classes": ""
                },
                "region_1": {
                    "label": "Content",
                    "name": "mini-content",
                    "region_class_enable": 0,
                    "classes": ""
                }
            }
        }
    }
}
```
</details>

### layout.mini_layouts.mini_sidebar.json
<details>

```json
{
    "_config_name": "layout.mini_layouts.mini_sidebar",
    "path": "node/%",
    "name": "mini_sidebar",
    "block_title": "",
    "title": "Mini Sidebar",
    "description": "",
    "renderer_name": "standard",
    "module": "mini_layouts",
    "weight": 0,
    "storage": 2,
    "layout_template": "mini_content_sidebar",
    "disabled": false,
    "settings": {
        "title": "",
        "title_display": "default",
        "title_block": null
    },
    "positions": {
        "089793f2-3501-40ef-b800-d0d8a53c545b--0": [
            "974646cf-16a1-49ab-b400-f759186f9e16"
        ],
        "089793f2-3501-40ef-b800-d0d8a53c545b--1": [
            "d97bba9d-7f75-4ce7-992b-4364c8534726"
        ],
        "title": []
    },
    "contexts": [],
    "relationships": [],
    "content": {
        "974646cf-16a1-49ab-b400-f759186f9e16": {
            "plugin": "field:field_block:node-field_image",
            "data": {
                "status": 1,
                "module": "field",
                "delta": "field_block",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "label": "hidden",
                    "formatter": "image",
                    "formatter_settings": {
                        "image_style": "",
                        "image_link": "",
                        "image_float": "",
                        "image_load": "auto"
                    },
                    "delta_offset": 0,
                    "delta_limit": "",
                    "delta_reversed": 0,
                    "admin_label": "",
                    "admin_description": ""
                },
                "uuid": "974646cf-16a1-49ab-b400-f759186f9e16",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "d97bba9d-7f75-4ce7-992b-4364c8534726": {
            "plugin": "system:main",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "main",
                "settings": {
                    "title_display": "none",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "admin_label": "",
                    "admin_description": ""
                },
                "uuid": "d97bba9d-7f75-4ce7-992b-4364c8534726",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        }
    }
}

```
</details>

### layout.layout.article.json
<details>

```json
{
    "_config_name": "layout.layout.article",
    "path": "node/%",
    "name": "article",
    "title": "Article",
    "description": null,
    "renderer_name": "standard",
    "module": null,
    "weight": 0,
    "storage": 1,
    "layout_template": "boxton",
    "disabled": false,
    "settings": {
        "title": "",
        "title_display": "default",
        "title_block": null
    },
    "positions": {
        "header": [
            "9017c335-8a91-4fba-8426-38747f19780b",
            "d3883e89-ec40-4e4f-a200-afcf762560fa"
        ],
        "top": [
            "812f1b74-32c3-44e7-bf06-6be0d3375547",
            "f47addfc-0fcc-4100-a000-c87723d082ac"
        ],
        "content": [
            "33ac8271-3269-45a9-bc00-b01963f8bcb5"
        ],
        "bottom": [],
        "footer": [
            "2f556c71-41b4-41a1-ab05-5a652d828f9f"
        ],
        "title": []
    },
    "contexts": [],
    "relationships": [],
    "content": {
        "9017c335-8a91-4fba-8426-38747f19780b": {
            "plugin": "system:header",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "header",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": {
                        "menu": "user-menu",
                        "logo": 1,
                        "site_name": 1,
                        "site_slogan": 1
                    },
                    "contexts": []
                },
                "uuid": "9017c335-8a91-4fba-8426-38747f19780b",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "d3883e89-ec40-4e4f-a200-afcf762560fa": {
            "plugin": "system:main-menu",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "main-menu",
                "settings": {
                    "title_display": "none",
                    "title": "",
                    "style": "default",
                    "block_settings": {
                        "style": "dropdown",
                        "level": 1,
                        "depth": 0
                    },
                    "contexts": []
                },
                "uuid": "d3883e89-ec40-4e4f-a200-afcf762560fa",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "812f1b74-32c3-44e7-bf06-6be0d3375547": {
            "plugin": "system:breadcrumb",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "breadcrumb",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": []
                },
                "uuid": "812f1b74-32c3-44e7-bf06-6be0d3375547",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "f47addfc-0fcc-4100-a000-c87723d082ac": {
            "plugin": "system:page_components:title_combo",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "page_components",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "title_tag": "h1",
                    "title_classes": "page-title",
                    "tab-type": "both",
                    "tab_type": "both"
                },
                "uuid": "f47addfc-0fcc-4100-a000-c87723d082ac",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "33ac8271-3269-45a9-bc00-b01963f8bcb5": {
            "plugin": "mini_layouts:mini_sidebar",
            "data": {
                "status": 1,
                "module": "mini_layouts",
                "delta": "mini_sidebar",
                "settings": {
                    "title_display": "none",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "admin_label": "",
                    "admin_description": ""
                },
                "uuid": "33ac8271-3269-45a9-bc00-b01963f8bcb5",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "2f556c71-41b4-41a1-ab05-5a652d828f9f": {
            "plugin": "system:powered-by",
            "data": {
                "status": 1,
                "module": "system",
                "delta": "powered-by",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": []
                },
                "uuid": "2f556c71-41b4-41a1-ab05-5a652d828f9f",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        }
    },
    "conditions": [
        {
            "plugin": "node_type",
            "data": {
                "settings": {
                    "bundles": [
                        "post"
                    ],
                    "load_condition_nojs": "Load condition"
                }
            }
        }
    ]
}
```
</details>

**Comment by indigoxela** [comment]
I tried to reproduce the weird display and was able to - in **Basis** ... and in Lateral. In Scenery, for example everything's fine.

It's caused by the "display-flex-column..." CSS on ".layout", which is similar in both themes. So that's a bug in Basis and in Lateral. Definitely not a bug in this module.

**Comment by yorkshire-pudding** [comment]
Thank you @indigoxela.  That's very helpful to know.  I'll try in another theme and see how I get on.  Any ideas why the field block would not be working?  I have `node/%` in both the master layout and the mini layout but it doesn't appear to get through to the mini layout. Should that be possible?  (the field image will work in the main layout)

**Comment by indigoxela** [comment]
> Any ideas why the field block would not be working?

No idea, it works fine here.

**Comment by indigoxela** [comment]
BTW: for Basis the following should work:

```
.layout .layout {
  display: block;
}
```
For Lateral see this commit: https://github.com/backdrop-contrib/lateral/commit/b2876e9eb22cc6e5e8a3da441fef5f684889dc69

**Comment by yorkshire-pudding** [comment]
Thanks. I don't normally use these themes so not an issue, but the field block is being a bit of a pain.  Any chance you can share the config files you have for getting a field block (as opposed to the main content block) to work within a mini layout?

**Comment by indigoxela** [comment]
> Any chance you can share the config files...

Yes, sure (if that helps).

<details><summary>Custom mini layout (json)</summary>
<pre>
{
    "_config_name": "layout.mini_layouts.custom_mini_post",
    "path": "node/%",
    "name": "custom_mini_post",
    "block_title": "",
    "title": "Custom Mini Post",
    "description": "",
    "renderer_name": "standard",
    "module": "mini_layouts",
    "weight": 0,
    "storage": 2,
    "layout_template": "miniflex",
    "disabled": false,
    "settings": {
        "title": "",
        "title_display": "default",
        "title_block": null
    },
    "positions": {
        "f89285ff-b134-4219-a400-ab2b9a8e4b29--0": [
            "506f5c0a-8ac1-4bf1-bb27-39c9b80ce281"
        ],
        "f89285ff-b134-4219-a400-ab2b9a8e4b29--1": [
            "0d54ca16-4bc3-47fe-9700-0dda5726ed4c"
        ],
        "title": []
    },
    "contexts": [],
    "relationships": [],
    "content": {
        "506f5c0a-8ac1-4bf1-bb27-39c9b80ce281": {
            "plugin": "field:field_block:node-body",
            "data": {
                "status": 1,
                "module": "field",
                "delta": "field_block",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "label": "hidden",
                    "formatter": "text_default",
                    "formatter_settings": [],
                    "delta_offset": 0,
                    "delta_limit": "",
                    "delta_reversed": 0,
                    "admin_label": "",
                    "admin_description": ""
                },
                "uuid": "506f5c0a-8ac1-4bf1-bb27-39c9b80ce281",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        },
        "0d54ca16-4bc3-47fe-9700-0dda5726ed4c": {
            "plugin": "field:field_block:node-field_image",
            "data": {
                "status": 1,
                "module": "field",
                "delta": "field_block",
                "settings": {
                    "title_display": "default",
                    "title": "",
                    "style": "default",
                    "block_settings": [],
                    "contexts": [],
                    "label": "hidden",
                    "formatter": "image",
                    "formatter_settings": {
                        "image_style": "medium",
                        "image_link": "",
                        "image_float": "",
                        "image_load": "auto"
                    },
                    "delta_offset": 0,
                    "delta_limit": "",
                    "delta_reversed": 0,
                    "admin_label": "",
                    "admin_description": ""
                },
                "uuid": "0d54ca16-4bc3-47fe-9700-0dda5726ed4c",
                "style": {
                    "plugin": "default",
                    "data": {
                        "settings": {
                            "classes": ""
                        }
                    }
                }
            }
        }
    }
}
</pre>
</details>

My suspicion: something with the field display settings. Or possibly you picked the wrong image field?

**Comment by yorkshire-pudding** [comment]
I found the issue.  I had created some other mini layouts testing the previous issue and even though they weren't included, perhaps that was the blocker.  If I have time, I'll try to reproduce to see if there is an issue.

Thank you @indigoxela - knowing that it should work helped me keep going
